spring:
  application:
    name: bar-stock
  datasource:
    url: jdbc:h2:mem:barstock;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
server:
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 8h
      cookie:
        http-only: true
        same-site: lax
  error:
    include-message: always

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
