spring:
  application:
    name: bar-stock
  datasource:
    url: jdbc:h2:mem:barstock;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: false
server:
  error:
    include-message: always

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/bar_stock?useSSL=false&serverTimezone=UTC}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate

