import ProductLink from './ProductLink'
import {useEffect,useState,type ReactNode} from 'react'
import {Navigate,NavLink,Route,Routes,useLocation} from 'react-router-dom'
import {api} from './api'
import {AuthGate,Account,Users} from './Auth'
import Stock from './Stock'
import Products from './Products'
import Invoices from './Invoices'
import Suppliers from './Suppliers'
import SalesReports from './SalesReports'
import ProductDetails from './ProductDetails'
import {stockUnit,pricedQuantity} from './inventory'
import type {DashboardData,Invoice,Product,Supplier,User} from './types'

const euro=new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'})
const icons={dashboard:'◫',stock:'▦',products:'▧',suppliers:'♙',invoices:'▤','sales-reports':'▥'}

export default function App(){return <AuthGate>{(user,onLogout)=><Inventory key={user.id} user={user} onLogout={onLogout}/>}</AuthGate>}
function Inventory({user,onLogout}:{user:User;onLogout:()=>void}){
 const location=useLocation(); const [products,setProducts]=useState<Product[]>([]);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [invoices,setInvoices]=useState<Invoice[]>([]);const [dashboard,setDashboard]=useState<DashboardData>();const [error,setError]=useState('');const [loading,setLoading]=useState(true)
 const reload=async()=>{setLoading(true);setError('');try{const [p,s,i,d]=await Promise.all([api.products(),api.suppliers(),api.invoices(),api.dashboard()]);setProducts(p);setSuppliers(s);setInvoices(i);setDashboard(d)}catch(e){setError(e instanceof Error?e.message:'Unable to load data')}finally{setLoading(false)}}
 useEffect(()=>{reload()},[])
 const title=location.pathname.startsWith('/products/')?'Detalle del producto':location.pathname==='/sales-reports'?'Reportes de ventas':location.pathname==='/products'?'Productos':location.pathname==='/users'?'Usuarios':location.pathname==='/stock'?'Stock control':location.pathname==='/suppliers'?'Suppliers':location.pathname==='/invoices'?'Supplier invoices':'Dashboard'
 return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">B</span><div><strong>BarStock</strong><small>Inventory studio</small></div></div><nav>{Object.entries(user.role==='ADMIN'?{...icons,users:'♙'}:icons).map(([key,icon])=><NavLink key={key} to={key==='dashboard'?'/':`/${key}`} end={key==='dashboard'}><span>{icon}</span>{{dashboard:'Dashboard',stock:'Stock',products:'Productos',suppliers:'Proveedores',invoices:'Facturas','sales-reports':'Reportes de ventas',users:'Usuarios'}[key as 'dashboard'|'stock'|'products'|'suppliers'|'invoices'|'sales-reports'|'users']}</NavLink>)}</nav><div className="sidebar-foot"><div className="pulse"/><div><strong>System online</strong><small>Spring API connected</small></div></div></aside><main><header><div><p>OPERATIONS / {title.toUpperCase()}</p><h1>{title}</h1></div><Account user={user} onLogout={onLogout}/></header>{error&&<div className="error">{error}</div>}{loading?<div className="loading">Refreshing the bar…</div>:!dashboard?<button className="primary" onClick={reload}>Reintentar</button>:<Routes>{user.role==='ADMIN'&&<Route path="/users" element={<Users/>}/>}<Route path="/" element={<Dashboard data={dashboard!} products={products}/>}/><Route path="/products/:id" element={<ProductDetails products={products} suppliers={suppliers} invoices={invoices} reload={reload}/>}/><Route path="/products" element={<Products products={products} suppliers={suppliers} reload={reload}/>}/><Route path="/stock" element={<Stock products={products} reload={reload}/>}/><Route path="/suppliers" element={<Suppliers suppliers={suppliers} reload={reload}/>}/><Route path="/sales-reports" element={<SalesReports reload={reload}/>}/><Route path="/invoices" element={<Invoices invoices={invoices} products={products} suppliers={suppliers} reload={reload}/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}</main></div>
}

function Dashboard({data,products}:{data:DashboardData;products:Product[]}){const low=products.filter(p=>p.stock<=p.minimumStock);const margin=data.potentialRevenue?data.potentialProfit/data.potentialRevenue*100:0;return <><section className="hero"><div><p className="eyebrow">LIVE INVENTORY</p><h2>Know what you have.<br/><em>Protect every margin.</em></h2><p>One clear view of purchasing, stock levels and the profit sitting behind your bar.</p></div><div className="hero-orbit"><span>{Math.round(margin)}%</span><small>potential margin</small></div></section><section className="metrics"><Metric label="Stock value" value={euro.format(data.stockValue)} note="at current cost"/><Metric label="Potential revenue" value={euro.format(data.potentialRevenue)} note="from current stock"/><Metric label="Potential profit" value={euro.format(data.potentialProfit)} note={`${margin.toFixed(1)}% gross margin`} accent/><Metric label="Low stock" value={String(data.lowStockCount)} note={`of ${data.productCount} products`} warn={data.lowStockCount>0}/></section><section className="grid-two"><Card title="Needs attention" action={`${low.length} items`}><div className="attention-list">{low.length?low.map(p=><div key={p.id}><span className="product-icon">{p.category.slice(0,1)}</span><div><strong><ProductLink id={p.id} name={p.name}/></strong><small>SKU {p.sku} · minimum {p.minimumStock} {stockUnit(p)}</small></div><b>{p.stock} {stockUnit(p)}</b></div>):<p className="empty">Everything is comfortably stocked.</p>}</div></Card><Card title="Inventory mix" action="By value"><div className="mix">{products.map((p,i)=>{const max=Math.max(...products.map(x=>pricedQuantity(x)*x.costPrice));const val=pricedQuantity(p)*p.costPrice;return <div key={p.id}><p><span><ProductLink id={p.id} name={p.name}/><small className="dashboard-stock">{p.stock} {stockUnit(p)} disponibles</small></span><b>{euro.format(val)}</b></p><i><u style={{width:`${max?val/max*100:0}%`,background:['#d9ff62','#9bd7c0','#f2aa7e','#86a8ff'][i%4]}}/></i></div>})}</div></Card></section></>}

function Metric({label,value,note,accent,warn}:{label:string;value:string;note:string;accent?:boolean;warn?:boolean}){return <article className={`metric ${accent?'accent':''} ${warn?'warn':''}`}><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
function Card({title,action,children}:{title:string;action:string;children:ReactNode}){return <article className="card"><div className="card-head"><h3>{title}</h3><span>{action}</span></div>{children}</article>}
