import {useEffect,useState,type FormEvent,type ReactNode} from 'react'
import {Navigate,NavLink,Route,Routes,useLocation} from 'react-router-dom'
import {api} from './api'
import {AuthGate,Account,Users} from './Auth'
import Stock from './Stock'
import type {DashboardData,Invoice,Product,Supplier,User} from './types'

const euro=new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'})
const icons={dashboard:'◫',stock:'▦',suppliers:'♙',invoices:'▤'}

export default function App(){return <AuthGate>{(user,onLogout)=><Inventory key={user.id} user={user} onLogout={onLogout}/>}</AuthGate>}
function Inventory({user,onLogout}:{user:User;onLogout:()=>void}){
 const location=useLocation(); const [products,setProducts]=useState<Product[]>([]);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [invoices,setInvoices]=useState<Invoice[]>([]);const [dashboard,setDashboard]=useState<DashboardData>();const [error,setError]=useState('');const [loading,setLoading]=useState(true)
 const reload=async()=>{setLoading(true);setError('');try{const [p,s,i,d]=await Promise.all([api.products(),api.suppliers(),api.invoices(),api.dashboard()]);setProducts(p);setSuppliers(s);setInvoices(i);setDashboard(d)}catch(e){setError(e instanceof Error?e.message:'Unable to load data')}finally{setLoading(false)}}
 useEffect(()=>{reload()},[])
 const title=location.pathname==='/users'?'Usuarios':location.pathname==='/stock'?'Stock control':location.pathname==='/suppliers'?'Suppliers':location.pathname==='/invoices'?'Supplier invoices':'Dashboard'
 return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">B</span><div><strong>BarStock</strong><small>Inventory studio</small></div></div><nav>{Object.entries(user.role==='ADMIN'?{...icons,users:'♙'}:icons).map(([key,icon])=><NavLink key={key} to={key==='dashboard'?'/':`/${key}`} end={key==='dashboard'}><span>{icon}</span>{key[0].toUpperCase()+key.slice(1)}</NavLink>)}</nav><div className="sidebar-foot"><div className="pulse"/><div><strong>System online</strong><small>Spring API connected</small></div></div></aside><main><header><div><p>OPERATIONS / {title.toUpperCase()}</p><h1>{title}</h1></div><Account user={user} onLogout={onLogout}/></header>{error&&<div className="error">{error}</div>}{loading?<div className="loading">Refreshing the bar…</div>:!dashboard?<button className="primary" onClick={reload}>Reintentar</button>:<Routes>{user.role==='ADMIN'&&<Route path="/users" element={<Users/>}/>}<Route path="/" element={<Dashboard data={dashboard!} products={products}/>}/><Route path="/stock" element={<Stock products={products} suppliers={suppliers} reload={reload}/>}/><Route path="/suppliers" element={<Suppliers suppliers={suppliers} reload={reload}/>}/><Route path="/invoices" element={<Invoices invoices={invoices} products={products} suppliers={suppliers} reload={reload}/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}</main></div>
}

function Dashboard({data,products}:{data:DashboardData;products:Product[]}){const low=products.filter(p=>p.stock<=p.minimumStock);const margin=data.potentialRevenue?data.potentialProfit/data.potentialRevenue*100:0;return <><section className="hero"><div><p className="eyebrow">LIVE INVENTORY</p><h2>Know what you have.<br/><em>Protect every margin.</em></h2><p>One clear view of purchasing, stock levels and the profit sitting behind your bar.</p></div><div className="hero-orbit"><span>{Math.round(margin)}%</span><small>potential margin</small></div></section><section className="metrics"><Metric label="Stock value" value={euro.format(data.stockValue)} note="at current cost"/><Metric label="Potential revenue" value={euro.format(data.potentialRevenue)} note="from current stock"/><Metric label="Potential profit" value={euro.format(data.potentialProfit)} note={`${margin.toFixed(1)}% gross margin`} accent/><Metric label="Low stock" value={String(data.lowStockCount)} note={`of ${data.productCount} products`} warn={data.lowStockCount>0}/></section><section className="grid-two"><Card title="Needs attention" action={`${low.length} items`}><div className="attention-list">{low.length?low.map(p=><div key={p.id}><span className="product-icon">{p.category.slice(0,1)}</span><div><strong>{p.name}</strong><small>SKU {p.sku} · minimum {p.minimumStock} {p.unit}</small></div><b>{p.stock} {p.unit}</b></div>):<p className="empty">Everything is comfortably stocked.</p>}</div></Card><Card title="Inventory mix" action="By value"><div className="mix">{products.slice(0,5).map((p,i)=>{const max=Math.max(...products.map(x=>x.stock*x.costPrice));const val=p.stock*p.costPrice;return <div key={p.id}><p><span>{p.name}</span><b>{euro.format(val)}</b></p><i><u style={{width:`${max?val/max*100:0}%`,background:['#d9ff62','#9bd7c0','#f2aa7e','#86a8ff'][i%4]}}/></i></div>})}</div></Card></section></>}

function Metric({label,value,note,accent,warn}:{label:string;value:string;note:string;accent?:boolean;warn?:boolean}){return <article className={`metric ${accent?'accent':''} ${warn?'warn':''}`}><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
function Card({title,action,children}:{title:string;action:string;children:ReactNode}){return <article className="card"><div className="card-head"><h3>{title}</h3><span>{action}</span></div>{children}</article>}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>}

function Suppliers({suppliers,reload}:{suppliers:Supplier[];reload:()=>Promise<void>}){const[open,setOpen]=useState(false);return <><div className="toolbar"><p className="section-copy">Keep ordering contacts and account details together.</p><button className="primary" onClick={()=>setOpen(true)}>＋ Add supplier</button></div><div className="supplier-grid">{suppliers.map(s=><article key={s.id}><div className="supplier-avatar">{s.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><h3>{s.name}</h3><p>{s.contactName||'No contact person'}</p><dl><dt>Email</dt><dd>{s.email||'—'}</dd><dt>Phone</dt><dd>{s.phone||'—'}</dd><dt>Tax ID</dt><dd>{s.taxId||'—'}</dd></dl></article>)}</div>{open&&<SupplierForm onClose={()=>setOpen(false)} onDone={async()=>{setOpen(false);await reload()}}/>}</>}
function SupplierForm({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await api.createSupplier(f);onDone()}return <Modal title="Add a supplier" onClose={onClose}><form onSubmit={submit} className="form-grid"><label className="wide">Company name<input name="name" required/></label><label>Contact person<input name="contactName"/></label><label>Tax ID<input name="taxId"/></label><label>Email<input name="email" type="email"/></label><label>Phone<input name="phone"/></label><FormActions onClose={onClose}/></form></Modal>}

function Invoices({invoices,products,suppliers,reload}:{invoices:Invoice[];products:Product[];suppliers:Supplier[];reload:()=>Promise<void>}){const[open,setOpen]=useState(false);return <><div className="toolbar"><p className="section-copy">Recording an invoice updates product cost and stock automatically.</p><button className="primary" onClick={()=>setOpen(true)}>＋ Record invoice</button></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Supplier</th><th>Date</th><th>Items</th><th>Status</th><th>Total</th></tr></thead><tbody>{invoices.length?invoices.map(i=><tr key={i.id}><td><strong>{i.invoiceNumber}</strong></td><td>{i.supplier.name}</td><td>{new Date(i.invoiceDate+'T00:00:00').toLocaleDateString('en-IE')}</td><td>{i.items.length}</td><td><span className={`status ${i.status==='PAID'?'good':i.status==='OVERDUE'?'low':'pending'}`}>{i.status.toLowerCase()}</span></td><td><b>{euro.format(i.total)}</b></td></tr>):<tr><td colSpan={6} className="empty">No invoices yet. Record the first delivery.</td></tr>}</tbody></table></div>{open&&<InvoiceForm products={products} suppliers={suppliers} onClose={()=>setOpen(false)} onDone={async()=>{setOpen(false);await reload()}}/>}</>}
function InvoiceForm({products,suppliers,onClose,onDone}:{products:Product[];suppliers:Supplier[];onClose:()=>void;onDone:()=>void}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api.createInvoice({invoiceNumber:f.get('invoiceNumber'),supplierId:Number(f.get('supplierId')),invoiceDate:f.get('invoiceDate'),status:f.get('status'),notes:f.get('notes'),items:[{productId:Number(f.get('productId')),quantity:Number(f.get('quantity')),unitCost:Number(f.get('unitCost'))}]});onDone()}return <Modal title="Record supplier invoice" onClose={onClose}><form onSubmit={submit} className="form-grid"><label>Invoice number<input name="invoiceNumber" required/></label><label>Invoice date<input name="invoiceDate" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Supplier<select name="supplierId" required><option value="">Select</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Status<select name="status"><option value="PENDING">Pending</option><option value="PAID">Paid</option><option value="OVERDUE">Overdue</option></select></label><div className="wide line-box"><h4>Invoice line</h4><div><label>Product<select name="productId" required><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="0.001" step="0.001" required/></label><label>Unit cost (€)<input name="unitCost" type="number" min="0" step="0.01" required/></label></div></div><label className="wide">Notes<input name="notes" placeholder="Delivery reference or payment terms"/></label><FormActions onClose={onClose}/></form></Modal>}
function FormActions({onClose}:{onClose:()=>void}){return <div className="form-actions wide"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save</button></div>}
