import ProductLink from './ProductLink'
import {useEffect,useRef,useState,type ReactNode} from 'react'
import {Navigate,NavLink,Route,Routes,useLocation} from 'react-router-dom'
import {api} from './api'
import {AuthGate,Account,Users} from './Auth'
import Stock from './Stock'
import Products from './Products'
import Invoices from './Invoices'
import Suppliers from './Suppliers'
import SalesReports from './SalesReports'
import ProductDetails from './ProductDetails'
import {stockUnit,pricedQuantity} from './inventory'
import type {DashboardData,MonthMetrics,Invoice,Product,Supplier,User} from './types'

const euro=new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'})
const icons={dashboard:'◫',stock:'▦',products:'▧',suppliers:'♙',invoices:'▤','sales-reports':'▥'}

export default function App(){return <AuthGate>{(user,onLogout)=><Inventory key={user.id} user={user} onLogout={onLogout}/>}</AuthGate>}
function Inventory({user,onLogout}:{user:User;onLogout:()=>void}){
 const location=useLocation(); const [products,setProducts]=useState<Product[]>([]);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [invoices,setInvoices]=useState<Invoice[]>([]);const [dashboard,setDashboard]=useState<DashboardData>();const [error,setError]=useState('');const [loading,setLoading]=useState(true)
 const reload=async()=>{setLoading(true);setError('');try{const [p,s,i,d]=await Promise.all([api.products(),api.suppliers(),api.invoices(),api.dashboard()]);setProducts(p);setSuppliers(s);setInvoices(i);setDashboard(d)}catch(e){setError(e instanceof Error?e.message:'Unable to load data')}finally{setLoading(false)}}
 useEffect(()=>{reload()},[])
 const title=location.pathname.startsWith('/products/')?'Detalle del producto':location.pathname==='/sales-reports'?'Reportes de ventas':location.pathname==='/products'?'Productos':location.pathname==='/users'?'Usuarios':location.pathname==='/stock'?'Stock control':location.pathname==='/suppliers'?'Suppliers':location.pathname==='/invoices'?'Supplier invoices':'Dashboard'
 return <div className="app-shell"><aside><div className="brand"><span className="brand-mark">B</span><div><strong>BarStock</strong><small>Inventory studio</small></div></div><nav>{Object.entries(user.role==='ADMIN'?{...icons,users:'♙'}:icons).map(([key,icon])=><NavLink key={key} to={key==='dashboard'?'/':`/${key}`} end={key==='dashboard'}><span>{icon}</span>{{dashboard:'Dashboard',stock:'Stock',products:'Productos',suppliers:'Proveedores',invoices:'Facturas','sales-reports':'Reportes de ventas',users:'Usuarios'}[key as 'dashboard'|'stock'|'products'|'suppliers'|'invoices'|'sales-reports'|'users']}</NavLink>)}</nav><div className="sidebar-foot"><div className="pulse"/><div><strong>System online</strong><small>Spring API connected</small></div></div></aside><main><header><div><p>OPERATIONS / {title.toUpperCase()}</p><h1>{title}</h1></div><Account user={user} onLogout={onLogout}/></header>{error&&<div className="error">{error}</div>}{loading?<div className="loading">Refreshing the bar…</div>:!dashboard?<button className="primary" onClick={reload}>Reintentar</button>:<Routes>{user.role==='ADMIN'&&<Route path="/users" element={<Users/>}/>}<Route path="/" element={<Dashboard data={dashboard!} products={products}/>}/><Route path="/products/:id" element={<ProductDetails products={products} suppliers={suppliers} invoices={invoices} reload={reload}/>}/><Route path="/products" element={<Products products={products} suppliers={suppliers} reload={reload}/>}/><Route path="/stock" element={<Stock products={products} reload={reload}/>}/><Route path="/suppliers" element={<Suppliers suppliers={suppliers} reload={reload}/>}/><Route path="/sales-reports" element={<SalesReports reload={reload}/>}/><Route path="/invoices" element={<Invoices invoices={invoices} products={products} suppliers={suppliers} reload={reload}/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}</main></div>
}

function monthLabel(value:string){const [year,month]=value.split('-');return `${['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'][Number(month)-1]} ${year}`}
function changeLabel(current:number,previous:number){if(!previous)return current?'Sin base anterior':'Sin actividad';const value=(current-previous)/Math.abs(previous)*100;return `${value>=0?'+':''}${value.toFixed(1)}% vs. mes pasado`}
function ComparisonChart({title,note,previous,current,value}:{title:string;note:string;previous:MonthMetrics;current:MonthMetrics;value:'sales'|'purchases'|'profit'}){const a=previous[value],b=current[value],max=Math.max(Math.abs(a),Math.abs(b),1);return <article className="monthly-chart"><div className="monthly-chart-head"><div><h3>{title}</h3><small>{note}</small></div><span className={value==='purchases'?'neutral':b-a>=0?'up':'down'}>{changeLabel(b,a)}</span></div><div className="month-bar-row"><div><strong>{monthLabel(previous.startDate)}</strong><b>{euro.format(a)}</b></div><i><u className={`${value} ${a<0?'negative':''}`} style={{width:`${Math.abs(a)/max*100}%`}}/></i></div><div className="month-bar-row current"><div><strong>{monthLabel(current.startDate)}</strong><b>{euro.format(b)}</b></div><i><u className={`${value} ${b<0?'negative':''}`} style={{width:`${Math.abs(b)/max*100}%`}}/></i></div></article>}
function CombinedMonthlyChart({previous,current}:{previous:MonthMetrics;current:MonthMetrics}){const rows=[{key:'sales' as const,label:'Ventas'},{key:'purchases' as const,label:'Compras'},{key:'profit' as const,label:'Profit'}];const max=Math.max(1,...rows.flatMap(row=>[Math.abs(previous[row.key]),Math.abs(current[row.key])]));const bar=(value:number,x:number,color:string)=>{const height=Math.max(value===0?2:Math.abs(value)/max*92,2);const y=value>=0?145-height:145;return <rect x={x} y={y} width="42" height={height} rx="6" fill={value<0?'#d6745b':color}><title>{euro.format(value)}</title></rect>};return <div className="combined-chart"><div className="chart-legend"><span><i className="previous"/>{monthLabel(previous.startDate)}</span><span><i className="current"/>{monthLabel(current.startDate)}</span></div><svg viewBox="0 0 720 270" role="img" aria-label={`Gráfico comparativo de ventas, compras y profit de ${monthLabel(previous.startDate)} y ${monthLabel(current.startDate)}`}><line x1="45" y1="145" x2="690" y2="145" className="chart-axis"/>{rows.map((row,index)=>{const center=145+index*215;return <g key={row.key}>{bar(previous[row.key],center-47,'#b8c4d9')}{bar(current[row.key],center+5,['#86a8ff','#f2aa7e','#70c58f'][index])}<text x={center} y="255" textAnchor="middle">{row.label}</text></g>})}</svg><div className="chart-values">{rows.map(row=><div key={row.key}><strong>{row.label}</strong><span>{euro.format(previous[row.key])}</span><b>{euro.format(current[row.key])}</b></div>)}</div></div>}
function MonthlyComparison({previous,current}:{previous:MonthMetrics;current:MonthMetrics}){const track=useRef<HTMLDivElement>(null);const [page,setPage]=useState(0);const go=(next:number)=>{const target=Math.max(0,Math.min(1,next));track.current?.children[target]?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'start'});setPage(target)};return <><div className="monthly-carousel-nav"><span>Desliza horizontalmente para cambiar la vista</span><div><button type="button" aria-label="Ver tarjetas" onClick={()=>go(0)} disabled={page===0}>←</button><button type="button" aria-label="Ver gráfico" onClick={()=>go(1)} disabled={page===1}>→</button></div></div><div className="monthly-carousel" ref={track} onScroll={event=>{const el=event.currentTarget;setPage(Math.round(el.scrollLeft/el.clientWidth))}}><div className="monthly-slide"><div className="monthly-charts"><ComparisonChart title="Ventas estimadas" note="Unidades vendidas × precio registrado" previous={previous} current={current} value="sales"/><ComparisonChart title="Compras de stock" note="Total de facturas recibidas" previous={previous} current={current} value="purchases"/><ComparisonChart title="Profit estimado" note="Ventas menos compras del mes" previous={previous} current={current} value="profit"/></div></div><div className="monthly-slide"><CombinedMonthlyChart previous={previous} current={current}/></div></div><div className="carousel-dots" aria-label="Vista seleccionada"><button className={page===0?'active':''} onClick={()=>go(0)} aria-label="Tarjetas"/><button className={page===1?'active':''} onClick={()=>go(1)} aria-label="Gráfico"/></div></>}
function Dashboard({data,products}:{data:DashboardData;products:Product[]}){const low=products.filter(p=>p.stock<=p.minimumStock);const margin=data.potentialRevenue?data.potentialProfit/data.potentialRevenue*100:0;const {previous,current}=data.monthlyComparison;return <><section className="monthly-overview"><div className="monthly-overview-head"><div><p className="eyebrow">COMPARACIÓN MENSUAL</p><h2>Ventas, compras y profit</h2><p>Mes actual frente al mes pasado, calculado con reportes de ventas aplicados y facturas de stock.</p></div><div className="report-coverage"><strong>{current.appliedReportCount}</strong><small>reportes aplicados en {monthLabel(current.startDate)}</small></div></div><MonthlyComparison previous={previous} current={current}/><p className="monthly-method">Los reportes semanales que cruzan de mes se distribuyen proporcionalmente por días. Los precios de venta se guardan al cargar cada reporte.</p></section><section className="metrics"><Metric label="Valor del stock" value={euro.format(data.stockValue)} note="al último costo de compra"/><Metric label="Ingresos potenciales" value={euro.format(data.potentialRevenue)} note="del stock actual"/><Metric label="Beneficio potencial" value={euro.format(data.potentialProfit)} note={`${margin.toFixed(1)}% de margen bruto`} accent/><Metric label="Stock bajo" value={String(data.lowStockCount)} note={`${data.productCount} productos en total`} warn={data.lowStockCount>0}/></section><section className="grid-two"><Card title="Necesitan atención" action={`${low.length} ítems`}><div className="attention-list">{low.length?low.map(p=><div key={p.id}><span className="product-icon">{p.category.slice(0,1)}</span><div><strong><ProductLink id={p.id} name={p.name}/></strong><small>SKU {p.sku} · mínimo {p.minimumStock} {stockUnit(p)}</small></div><b>{p.stock} {stockUnit(p)}</b></div>):<p className="empty">El stock está en niveles adecuados.</p>}</div></Card><Card title="Composición del inventario" action="Por valor"><div className="mix">{products.map((p,i)=>{const max=Math.max(...products.map(x=>pricedQuantity(x)*x.costPrice));const val=pricedQuantity(p)*p.costPrice;return <div key={p.id}><p><span><ProductLink id={p.id} name={p.name}/><small className="dashboard-stock">{p.stock} {stockUnit(p)} disponibles</small></span><b>{euro.format(val)}</b></p><i><u style={{width:`${max?val/max*100:0}%`,background:['#d9ff62','#9bd7c0','#f2aa7e','#86a8ff'][i%4]}}/></i></div>})}</div></Card></section></>}
function Metric({label,value,note,accent,warn}:{label:string;value:string;note:string;accent?:boolean;warn?:boolean}){return <article className={`metric ${accent?'accent':''} ${warn?'warn':''}`}><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
function Card({title,action,children}:{title:string;action:string;children:ReactNode}){return <article className="card"><div className="card-head"><h3>{title}</h3><span>{action}</span></div>{children}</article>}
