import {useState,useEffect,type FormEvent,type ReactNode} from 'react'
import {api,productImage} from './api'
import type {Product,Supplier} from './types'
import {purchaseUnit} from './inventory'
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button aria-label="Cerrar" onClick={onClose}>×</button></div>{children}</div></div>}
export default function Products({products,suppliers,reload}:{products:Product[];suppliers:Supplier[];reload:()=>Promise<void>}){
 const [editor,setEditor]=useState<Product|'new'>()
 return <><div className="toolbar"><p className="section-copy">Crea los ítems del catálogo. El stock ingresa mediante facturas.</p><button className="primary" onClick={()=>setEditor('new')}>＋ Agregar producto</button></div><div className="table-wrap"><table><thead><tr><th>Producto</th><th>SKU</th><th>Formato</th><th>Proveedor</th><th>Acciones</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><div className="product-cell">{p.imageVersion?<img className="product-photo" src={productImage(p)} alt={p.name}/>:<span className="product-photo placeholder">{p.name.slice(0,1)}</span>}<strong>{p.name}</strong></div></td><td>{p.sku}</td><td>{purchaseUnit(p)}</td><td>{p.supplier?.name||'Sin proveedor'}</td><td><button className="ghost" onClick={()=>setEditor(p)}>Editar ítem</button></td></tr>)}{!products.length&&<tr><td colSpan={5} className="empty">Agrega tu primer producto y luego registra su factura.</td></tr>}</tbody></table></div>{editor&&<ProductForm product={editor==='new'?undefined:editor} suppliers={suppliers} onClose={()=>setEditor(undefined)} onDone={async()=>{setEditor(undefined);await reload()}}/>}</>
}
export function ProductForm({product,suppliers,onClose,onDone}:{product?:Product;suppliers:Supplier[];onClose:()=>void;onDone:()=>Promise<void>}){
 const [unit,setUnit]=useState(product?.unit||'unit')
 const [file,setFile]=useState<File>(),[preview,setPreview]=useState(''),[remove,setRemove]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[savedId,setSavedId]=useState(product?.id)
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file])
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setError('');const f=new FormData(e.currentTarget)
  if(file&&(file.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))){setError('Selecciona una imagen PNG, JPEG o WebP de hasta 2 MB.');return}
  setBusy(true)
  try{
   const body={sku:f.get('sku'),name:f.get('name'),category:f.get('category'),unit,kegSizeLitres:unit==='keg'?Number(f.get('kegSizeLitres')):null,minimumStock:Number(f.get('minimumStock')),sellingPrice:Number(f.get('sellingPrice')),supplierId:Number(f.get('supplierId'))||null,active:product?.active??true}
   const saved=savedId?await api.updateProduct(savedId,body):await api.createProduct(body);setSavedId(saved.id)
   try{if(file)await api.uploadImage(saved.id,file);else if(remove&&product?.imageVersion)await api.deleteImage(saved.id)}catch(e){throw new Error(`El producto se guardó, pero la imagen no pudo actualizarse. ${e instanceof Error?e.message:''} Puedes volver a guardar sin crear un duplicado.`)}
   await onDone()
  }catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}
 }
 return <Modal title={product?'Editar producto':'Agregar producto'} onClose={()=>{if(!busy)onClose()}}><form onSubmit={submit} className="form-grid">{error&&<div className="wide error" role="alert">{error}</div>}<p className="wide form-note">El producto se crea sin stock. Las cantidades y el costo se cargan al registrar una factura.</p><label className="wide">Nombre<input name="name" required maxLength={140} defaultValue={product?.name}/></label><label>SKU<input name="sku" required maxLength={50} defaultValue={product?.sku}/></label><label>Categoría<input name="category" required maxLength={80} defaultValue={product?.category}/></label><label>Formato<select name="unit" value={unit} onChange={e=>setUnit(e.target.value)}><option value="unit">Unidad</option><option value="bottle">Botella</option><option value="case">Caja</option><option value="L">Litros</option><option value="keg">Keg (stock en litros)</option>{!['unit','bottle','case','L','keg'].includes(unit)&&<option value={unit}>{unit}</option>}</select></label>{unit==='keg'&&<label>Tamaño del keg<select name="kegSizeLitres" defaultValue={product?.kegSizeLitres||50}><option value="50">50 L keg</option><option value="30">30 L keg</option><option value="20">20 L keg</option></select></label>}<label className="wide">Proveedor<select name="supplierId" defaultValue={product?.supplier?.id||''}><option value="">Sin proveedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Stock mínimo {unit==='keg'?'(L)':`(${unit})`}<input name="minimumStock" type="number" min="0" step="0.001" defaultValue={product?.minimumStock||0} required/></label><label>Precio de venta (€) {unit==='keg'?'por keg': 'por unidad'}<input name="sellingPrice" type="number" min="0" step="0.01" defaultValue={product?.sellingPrice} required/></label><section className="wide image-editor"><label>Imagen del producto<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]);setRemove(false)}}/><small>PNG, JPEG o WebP · hasta 2 MB</small></label>{(preview||product?.imageVersion)&&!remove&&<><img className="image-preview" src={preview||(product?productImage(product):'')} alt="Vista previa del producto"/><button type="button" className="ghost" disabled={busy} onClick={()=>{setFile(undefined);setRemove(true)}}>Quitar imagen</button></>}</section><div className="wide form-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar producto'}</button></div></form></Modal>
}
