import {useMemo,useState,useEffect,type FormEvent,type ReactNode} from 'react'
import {api,productImage} from './api'
import type {Product,Supplier} from './types'
import {stockUnit,pricedQuantity} from './inventory'
const euro=new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'})
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="modal-head"><h2>{title}</h2><button aria-label="Cerrar" onClick={onClose}>×</button></div>{children}</div></div>}
export default function Stock({products,suppliers,reload}:{products:Product[];suppliers:Supplier[];reload:()=>Promise<void>}){
 const [query,setQuery]=useState(''),[editor,setEditor]=useState<Product|'new'>(),[adjust,setAdjust]=useState<Product>()
 const filtered=useMemo(()=>products.filter(p=>[p.name,p.sku,p.category,p.supplier?.name].join(' ').toLowerCase().includes(query.toLowerCase())),[products,query])
 return <><div className="toolbar"><div className="search">⌕<input aria-label="Buscar productos" placeholder="Buscar por nombre, SKU o proveedor" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="primary" onClick={()=>setEditor('new')}>＋ Agregar producto</button></div><div className="table-wrap"><table><thead><tr><th>Producto</th><th>Categoría</th><th>Stock</th><th>Costo</th><th>Precio</th><th>Margen</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filtered.map(p=>{const margin=p.sellingPrice?(p.sellingPrice-p.costPrice)/p.sellingPrice*100:0;const low=p.stock<=p.minimumStock;return <tr key={p.id}><td><div className="product-cell">{p.imageVersion?<img className="product-photo" src={productImage(p)} alt={p.name}/>:<span className="product-photo placeholder">{p.name.slice(0,1)}</span>}<div><strong>{p.name}</strong><small>{p.sku} · {p.supplier?.name||'Sin proveedor'}</small></div></div></td><td>{p.category}</td><td><b>{p.stock}</b> {stockUnit(p)}{p.unit==='keg'&&<small>{pricedQuantity(p).toFixed(2)} kegs de {p.kegSizeLitres} L</small>}</td><td>{euro.format(p.costPrice)}{p.unit==='keg'&&<small>por keg de {p.kegSizeLitres} L</small>}</td><td>{euro.format(p.sellingPrice)}{p.unit==='keg'&&<small>por keg de {p.kegSizeLitres} L</small>}</td><td className="profit">{margin.toFixed(0)}%</td><td><span className={`status ${low?'low':'good'}`}>{low?'Stock bajo':'Disponible'}</span></td><td><div className="row-actions"><button className="ghost" onClick={()=>setEditor(p)}>Editar</button><button className="ghost" onClick={()=>setAdjust(p)}>Ajustar</button></div></td></tr>})}{!filtered.length&&<tr><td className="empty" colSpan={8}>No se encontraron productos.</td></tr>}</tbody></table></div>{editor&&<ProductForm product={editor==='new'?undefined:editor} suppliers={suppliers} onClose={()=>setEditor(undefined)} onDone={async()=>{setEditor(undefined);await reload()}}/>}{adjust&&<AdjustForm product={adjust} onClose={()=>setAdjust(undefined)} onDone={async()=>{setAdjust(undefined);await reload()}}/>}</>
}
function ProductForm({product,suppliers,onClose,onDone}:{product?:Product;suppliers:Supplier[];onClose:()=>void;onDone:()=>Promise<void>}){
 const [unit,setUnit]=useState(product?.unit||'unit')
 const [file,setFile]=useState<File>(),[preview,setPreview]=useState(''),[remove,setRemove]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[savedId,setSavedId]=useState(product?.id)
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file])
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setError('');const f=new FormData(e.currentTarget)
  if(file&&(file.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))){setError('Selecciona una imagen PNG, JPEG o WebP de hasta 2 MB.');return}
  setBusy(true)
  try{
   const body={sku:f.get('sku'),name:f.get('name'),category:f.get('category'),unit,kegSizeLitres:unit==='keg'?Number(f.get('kegSizeLitres')):null,stock:Number(f.get('stock')),minimumStock:Number(f.get('minimumStock')),costPrice:Number(f.get('costPrice')),sellingPrice:Number(f.get('sellingPrice')),supplierId:Number(f.get('supplierId'))||null,active:product?.active??true}
   const saved=savedId?await api.updateProduct(savedId,body):await api.createProduct(body);setSavedId(saved.id)
   try{if(file)await api.uploadImage(saved.id,file);else if(remove&&product?.imageVersion)await api.deleteImage(saved.id)}catch(e){throw new Error(`El producto se guardó, pero la imagen no pudo actualizarse. ${e instanceof Error?e.message:''} Puedes volver a guardar sin crear un duplicado.`)}
   await onDone()
  }catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.')}finally{setBusy(false)}
 }
 return <Modal title={product?'Editar producto':'Agregar producto'} onClose={()=>{if(!busy)onClose()}}><form onSubmit={submit} className="form-grid">{error&&<div className="wide error" role="alert">{error}</div>}<label className="wide">Nombre<input name="name" required maxLength={140} defaultValue={product?.name}/></label><label>SKU<input name="sku" required maxLength={50} defaultValue={product?.sku}/></label><label>Categoría<input name="category" required maxLength={80} defaultValue={product?.category}/></label><label>Formato<select name="unit" value={unit} onChange={e=>setUnit(e.target.value)}><option value="unit">Unidad</option><option value="bottle">Botella</option><option value="case">Caja</option><option value="L">Litros</option><option value="keg">Keg (stock en litros)</option>{!['unit','bottle','case','L','keg'].includes(unit)&&<option value={unit}>{unit}</option>}</select></label>{unit==='keg'&&<label>Tamaño del keg<select name="kegSizeLitres" defaultValue={product?.kegSizeLitres||50}><option value="50">50 L keg</option><option value="30">30 L keg</option><option value="20">20 L keg</option></select></label>}<label className="wide">Proveedor<select name="supplierId" defaultValue={product?.supplier?.id||''}><option value="">Sin proveedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Stock actual {unit==='keg'?'(L)':`(${unit})`}<input name="stock" type="number" min="0" step="0.001" defaultValue={product?.stock||0} required/></label><label>Stock mínimo {unit==='keg'?'(L)':`(${unit})`}<input name="minimumStock" type="number" min="0" step="0.001" defaultValue={product?.minimumStock||0} required/></label><label>Costo (€) {unit==='keg'?'por keg': 'por unidad'}<input name="costPrice" type="number" min="0" step="0.01" defaultValue={product?.costPrice} required/></label><label>Precio de venta (€) {unit==='keg'?'por keg': 'por unidad'}<input name="sellingPrice" type="number" min="0" step="0.01" defaultValue={product?.sellingPrice} required/></label><section className="wide image-editor"><label>Imagen del producto<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]);setRemove(false)}}/><small>PNG, JPEG o WebP · hasta 2 MB</small></label>{(preview||product?.imageVersion)&&!remove&&<><img className="image-preview" src={preview||(product?productImage(product):'')} alt="Vista previa del producto"/><button type="button" className="ghost" disabled={busy} onClick={()=>{setFile(undefined);setRemove(true)}}>Quitar imagen</button></>}</section><div className="wide form-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar producto'}</button></div></form></Modal>
}
function AdjustForm({product,onClose,onDone}:{product:Product;onClose:()=>void;onDone:()=>Promise<void>}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await api.adjustStock(product.id,{quantity:Number(f.get('quantity')),reason:f.get('reason')});await onDone()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
 return <Modal title={`Ajustar ${product.name}`} onClose={()=>{if(!busy)onClose()}}><form onSubmit={submit} className="form-grid">{error&&<div className="wide error" role="alert">{error}</div>}<p className="wide form-note">Stock actual: {product.stock} {stockUnit(product)} · SKU {product.sku}</p><label>Cambio de cantidad ({stockUnit(product)})<input name="quantity" type="number" step="0.001" required/></label><label>Motivo<input name="reason" required/></label><div className="wide form-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar'}</button></div></form></Modal>
}
