import ProductLink from './ProductLink'
import {useMemo,useState,type FormEvent,type ReactNode} from 'react'
import {api,productImage} from './api'
import {NavLink} from 'react-router-dom'
import type {Product} from './types'
import {stockUnit,pricedQuantity} from './inventory'
const euro=new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'})
function Modal({title,children,onClose}:{title:ReactNode;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label={typeof title==='string'?title:'Ajustar stock'}><div className="modal-head"><h2>{title}</h2><button aria-label="Cerrar" onClick={onClose}>×</button></div>{children}</div></div>}
export default function Stock({products,reload}:{products:Product[];reload:()=>Promise<void>}){
 const [query,setQuery]=useState(''),[adjust,setAdjust]=useState<Product>()
 const filtered=useMemo(()=>products.filter(p=>[p.name,p.sku,p.category,...p.supplierSkus.flatMap(entry=>[entry.supplier.name,entry.sku])].join(' ').toLowerCase().includes(query.toLowerCase())),[products,query])
 return <><div className="toolbar"><div className="search">⌕<input aria-label="Buscar productos" placeholder="Buscar por nombre, SKU o proveedor" value={query} onChange={e=>setQuery(e.target.value)}/></div><NavLink className="primary" to="/invoices">＋ Cargar factura</NavLink></div><div className="table-wrap"><table><thead><tr><th>Producto</th><th>Categoría</th><th>Stock</th><th>Costo</th><th>Precio</th><th>Margen</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filtered.map(p=>{const margin=p.sellingPrice?(p.sellingPrice-p.costPrice)/p.sellingPrice*100:0;const low=p.stock<=p.minimumStock;return <tr key={p.id}><td><div className="product-cell">{p.imageVersion?<img className="product-photo" src={productImage(p)} alt={p.name}/>:<span className="product-photo placeholder">{p.name.slice(0,1)}</span>}<div><strong><ProductLink id={p.id} name={p.name}/></strong><small>{p.sku} · {p.supplierSkus.map(entry=>entry.supplier.name+' ('+entry.sku+')').join(', ')||'Sin proveedor'}</small></div></div></td><td>{p.category}</td><td><b>{p.stock}</b> {stockUnit(p)}{p.unit==='keg'&&<small>{pricedQuantity(p).toFixed(2)} kegs de {p.kegSizeLitres} L</small>}</td><td>{euro.format(p.costPrice)}{p.unit==='keg'&&<small>por keg de {p.kegSizeLitres} L</small>}</td><td>{euro.format(p.sellingPrice)}{p.unit==='keg'&&<small>por keg de {p.kegSizeLitres} L</small>}</td><td className="profit">{margin.toFixed(0)}%</td><td><span className={`status ${low?'low':'good'}`}>{low?'Stock bajo':'Disponible'}</span></td><td><div className="row-actions"><button className="ghost" onClick={()=>setAdjust(p)}>Ajustar</button></div></td></tr>})}{!filtered.length&&<tr><td className="empty" colSpan={8}>No se encontraron productos.</td></tr>}</tbody></table></div>{adjust&&<AdjustForm product={adjust} onClose={()=>setAdjust(undefined)} onDone={async()=>{setAdjust(undefined);await reload()}}/>}</>
}
function AdjustForm({product,onClose,onDone}:{product:Product;onClose:()=>void;onDone:()=>Promise<void>}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await api.adjustStock(product.id,{quantity:Number(f.get('quantity')),reason:f.get('reason')});await onDone()}catch(e){setError(e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
 return <Modal title={<>Ajustar <ProductLink id={product.id} name={product.name}/></>} onClose={()=>{if(!busy)onClose()}}><form onSubmit={submit} className="form-grid">{error&&<div className="wide error" role="alert">{error}</div>}<p className="wide form-note">Stock actual: {product.stock} {stockUnit(product)} · SKU {product.sku}</p><label>Salida / consumo ({stockUnit(product)})<input name="quantity" type="number" step="0.001" max="-0.001" required/></label><label>Motivo<input name="reason" required/></label><div className="wide form-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar'}</button></div></form></Modal>
}
