import {useState,type FormEvent} from 'react'
import {api} from './api'
import type {Supplier} from './types'
export default function Suppliers({suppliers,reload}:{suppliers:Supplier[];reload:()=>Promise<void>}){
 const [editor,setEditor]=useState<Supplier|'new'>(),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const body=Object.fromEntries(new FormData(event.currentTarget));setBusy(true);setError('');try{if(editor==='new')await api.createSupplier(body);else if(editor)await api.updateSupplier(editor.id,body);setEditor(undefined);await reload()}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar el proveedor.')}finally{setBusy(false)}}
 const supplier=editor&&editor!=='new'?editor:undefined
 return <><div className="toolbar"><p className="section-copy">Administra los datos de contacto y los proveedores de tus productos.</p><button className="primary" onClick={()=>{setError('');setEditor('new')}}>＋ Agregar proveedor</button></div><div className="supplier-grid">{suppliers.map(s=><article key={s.id}><div className="supplier-avatar">{s.name.slice(0,2)}</div><h3>{s.name}</h3><p>{s.contactName||'Sin contacto'}</p><dl><dt>Email</dt><dd>{s.email||'—'}</dd><dt>Teléfono</dt><dd>{s.phone||'—'}</dd><dt>Tax ID</dt><dd>{s.taxId||'—'}</dd></dl><button className="ghost" onClick={()=>{setError('');setEditor(s)}}>Editar proveedor</button></article>)}</div>{editor&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Editar proveedor"><div className="modal-head"><h2>{supplier?'Editar proveedor':'Agregar proveedor'}</h2><button disabled={busy} onClick={()=>setEditor(undefined)}>×</button></div><form className="form-grid" onSubmit={submit}>{error&&<div className="wide error" role="alert">{error}</div>}<label className="wide">Nombre de empresa<input name="name" required defaultValue={supplier?.name} disabled={busy}/></label><label>Contacto<input name="contactName" defaultValue={supplier?.contactName} disabled={busy}/></label><label>Tax ID<input name="taxId" defaultValue={supplier?.taxId} disabled={busy}/></label><label>Email<input name="email" type="email" defaultValue={supplier?.email} disabled={busy}/></label><label>Teléfono<input name="phone" defaultValue={supplier?.phone} disabled={busy}/></label><div className="wide form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditor(undefined)}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar proveedor'}</button></div></form></section></div>}</>
}
